miguelchenriques/ES-2Sem-2021-Grupo2

src/main/java/es2sem2021/grupo2/codequalityassessor/metrics/extractors/CYCLO_method.java
src/test/java/es2sem2021/grupo2/codequalityassessor/metrics/extractors/CYCLO_methodTest.java

CYCLO_method update

---

src/main/java/es2sem2021/grupo2/codequalityassessor/metrics/extractors/LOC_method.java
src/test/java/es2sem2021/grupo2/codequalityassessor/metrics/extractors/LOC_methodTest.java

LOC_method antigo estava com alguns problemas, está corrigido agora.

LOC_method update

---

src/main/java/es2sem2021/grupo2/codequalityassessor/metrics/extractors/WMCClass.java
src/test/java/es2sem2021/grupo2/codequalityassessor/metrics/extractors/WMCClassTest.java

WMCClass Update

---

src/main/java/es2sem2021/grupo2/codequalityassessor/metrics/extractors/CYCLO_method.java

Cyclo methods update

---

src/test/java/es2sem2021/grupo2/codequalityassessor/rules/RuleSetTest.java

Created RuleSetTest to test the RulesSet class methods

RuleSetTest

---

src/main/java/es2sem2021/grupo2/codequalityassessor/metrics/extractors/WMCClass.java
src/test/java/es2sem2021/grupo2/codequalityassessor/metrics/extractors/WMCClassTest.java

WMC Class now counts inner classes as part of the main class

WMC Class  fix

---

src/main/java/es2sem2021/grupo2/codequalityassessor/metrics/extractors/WMCClass.java

WMC Class now counts inner classes as part of the main class

WMC Class fix

---

src/main/java/es2sem2021/grupo2/codequalityassessor/rules/RulesSet.java

Created a functions that imports mandatory rules

Import Mandatory Rules

---

src/main/java/es2sem2021/grupo2/codequalityassessor/rules/RulesSet.java
src/test/java/es2sem2021/grupo2/codequalityassessor/rules/RuleSetTest.java

Regras Junit test

---

src/main/java/es2sem2021/grupo2/codequalityassessor/rules/FinalResults.java
src/main/java/es2sem2021/grupo2/codequalityassessor/rules/RuleMethod.java
src/main/java/es2sem2021/grupo2/codequalityassessor/rules/RuleResults.java

Implementation of FinalResults and sub-classes

FinalResults

---

src/main/java/es2sem2021/grupo2/codequalityassessor/rules/FinalResults.java
src/test/java/es2sem2021/grupo2/codequalityassessor/rules/FinalResultsTest.java

Added JUnit Test to FinalResults
Debugged FinalResults

FinalResultsTesting

---

src/main/java/es2sem2021/grupo2/codequalityassessor/gui/App.java
src/main/java/es2sem2021/grupo2/codequalityassessor/gui/CodeSmellsPanel.java
src/main/java/es2sem2021/grupo2/codequalityassessor/gui/CodeSmellsTableGenerator.java
src/main/java/es2sem2021/grupo2/codequalityassessor/gui/ExtractPanel.java

GUI now has a table that shows the results of the Code Smells Detection

Results of Code Smells Detection- GUI

---

src/main/java/es2sem2021/grupo2/codequalityassessor/rules/CodeSmell.java
src/main/java/es2sem2021/grupo2/codequalityassessor/rules/CodeSmellSet.java
src/main/java/es2sem2021/grupo2/codequalityassessor/rules/RulesSet.java

Created CodeSmells Class and subclass

CodeSmells

---

src/main/java/es2sem2021/grupo2/codequalityassessor/rules/CodeSmells.java
src/main/java/es2sem2021/grupo2/codequalityassessor/rules/Constants.java
src/main/java/es2sem2021/grupo2/codequalityassessor/rules/Rule.java

Fixed bugs CodeSmells

---

src/main/java/es2sem2021/grupo2/codequalityassessor/rules/FinalResults.java
src/main/java/es2sem2021/grupo2/codequalityassessor/rules/RuleResults.java

Corrected bugs in FinalResults

Corrected FinalResults

---

src/test/java/es2sem2021/grupo2/codequalityassessor/rules/CodeSmellTest.java
src/test/java/es2sem2021/grupo2/codequalityassessor/rules/FinalResultsTest.java

Added CodeSmellTest and FinalResultsTest

Added CodeSmell and FinalResults Testing

---

src/test/java/es2sem2021/grupo2/codequalityassessor/rules/RuleTest.java

Removed SystemOut Prints from RuleTest

Removed SystemOut Prints from RuleTest

---

src/main/java/es2sem2021/grupo2/codequalityassessor/gui/App.java
src/main/java/es2sem2021/grupo2/codequalityassessor/gui/QualityEvaluationPanel.java

GUI Quality Eval

---

src/main/java/es2sem2021/grupo2/codequalityassessor/gui/CodeSmellsPanel.java
src/main/java/es2sem2021/grupo2/codequalityassessor/xlsx/CodeSmellsTableGenerator.java

CodeSmellsPanel now uses HashMap instead of ArrayList

Gui CodeSmellsPanel

---

src/main/java/es2sem2021/grupo2/codequalityassessor/gui/App.java
src/main/java/es2sem2021/grupo2/codequalityassessor/gui/CodeSmellsPanel.java
src/main/java/es2sem2021/grupo2/codequalityassessor/gui/CreateCodeSmellsPanel.java
src/main/java/es2sem2021/grupo2/codequalityassessor/rules/CodeSmells.java

added CreateCodeSmellsPanel that can add Code Smells and delete them

GUI- CreateCodeSmellsPanel 

---

src/main/java/es2sem2021/grupo2/codequalityassessor/rules/CodeSmells.java
src/main/java/es2sem2021/grupo2/codequalityassessor/rules/RulesSet.java

CodeSmells class
